# Generated by Django 5.0.6 on 2024-05-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("bid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("url", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ELEC", "Electronics"),
                            ("FASH", "Fashion"),
                            ("HOME", "Home"),
                            ("BOOK", "Books"),
                            ("TOYS", "Toys"),
                            ("OTH", "Other"),
                        ],
                        default="OTH",
                        max_length=5,
                    ),
                ),
            ],
        ),
    ]
