# Generated by Django 5.0.6 on 2024-05-22 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_owner_alter_listing_category_bidding"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
