# Generated by Django 5.0.6 on 2024-05-22 01:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidding",
            name="bid_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
