# Generated by Django 5.0.6 on 2024-06-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_bidding_bid_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                related_name="watched_by", to="auctions.listing"
            ),
        ),
    ]
