# Generated by Django 5.0.6 on 2024-07-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_listing_closed_date_listing_winner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="bid",
            new_name="start_price",
        ),
        migrations.AddField(
            model_name="listing",
            name="current_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
