# Generated by Django 5.0.6 on 2024-07-31 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_rename_bid_listing_start_price_listing_current_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidding",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.listing",
            ),
        ),
    ]
