# Generated by Django 5.0.6 on 2024-07-25 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_rename_bid_listing_start_price_listing_current_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="closed_date",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="winner",
        ),
        migrations.AlterField(
            model_name="bidding",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.listing",
            ),
        ),
        migrations.CreateModel(
            name="ClosedListing",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auctions.listing",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "closed_date",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner_listing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("auctions.listing",),
        ),
    ]
