# Generated by Django 5.0.6 on 2024-07-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_remove_listing_closed_date_remove_listing_winner_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ClosedListing",
        ),
    ]
