# Generated by Django 5.0.6 on 2024-07-25 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_delete_closedlisting"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosedListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("url", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OTH", "Other"),
                            ("ELEC", "Electronics"),
                            ("FASH", "Fashion"),
                            ("HOME", "Home"),
                            ("BOOK", "Books"),
                            ("TOYS", "Toys"),
                        ],
                        default="OTH",
                        max_length=5,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "current_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("closed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="won_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
